CV/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from CV_APP.views import cv, coordinacion, rectores


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CV_APP.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/coordinador/', coordinacion.CoordinadorSignUpView.as_view(), name='coordinador_signup'),
    path('accounts/rector/', rectores.RectorSignUpView.as_view(), name='rector_signup'),



]

CV_APP/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from .views import cv, coordinacion, rectores, psicologa
urlpatterns = [
    path('postulacion', cv.index, name='index'),
    path('', cv.home, name='home'),
    path('user_profile', cv.user_profile, name='user'),
    path('coordinacion/', include(([
        path('postulantes', coordinacion.index, name='index'),
        path('rechazados', coordinacion.rechazados, name='rechazados'),
        path('finalizado', coordinacion.finalizados, name='fin'),
        path('finalizados', coordinacion.finalizados_c, name='fin_c'),

        path('coordinadores', coordinacion.index_c, name='coordinadores'),
        path('coordinadores/entrevistar', coordinacion.entrevistar_c, name='entrevistar'),
        path('coordinadores/<int:pk>/rubrica/', coordinacion.rubrica, name='rubrica'),
        path('postulantes/<int:pk>/rubricas/', coordinacion.rubricas, name='rubricas'),

        path('postulantes/<int:pk>/rubrica_rector/', coordinacion.vista_rubrica, name='vista_rubrica'),
        path('coordinadores/<int:pk>/rubrica_coordinador/', coordinacion.vista_rubricaC, name='vista_rubrica_coordinador'),
        path('postulantes/<int:pk>/vista_rubrica_equipo/', coordinacion.vista_rubrica_equipo, name='vista_rubrica_equipo'),
        path('postulantes/<int:pk>/vista_rubrica_equipo/', coordinacion.vista_rubrica_equipo, name='vista_rubrica_equipo'),
        path('postulantes/<int:pk>/vista_rubrica_demo/', coordinacion.vista_rubrica_demo, name='vista_rubrica_demo'),
        path('activos', coordinacion.activos, name='activos'),
        path('proceso', coordinacion.proceso, name='proceso'),
        path('psicolaboral', coordinacion.psicolaboral, name='psicolaboral'),
        path('psicolaboral_coordinador', coordinacion.psicolaboral_c, name='psicolaboral_c'),

        path('postulantes/<int:pk>/', coordinacion.info, name='info'),
        path('postulantes/<int:pk>/delete', coordinacion.PostulanteDeleteView.as_view(), name='borrar'),
    ], 'CV_APP'), namespace='coordinacion')),

    path('rectores/', include(([
        path('postulantes', rectores.index, name='index'),
        path('postulantes/<int:pk>/', rectores.info, name='info'),
        path('postulantes/<int:pk>/', rectores.info2, name='informacion2'),
        path('postulantes/rechazados/', rectores.cargo, name='rechazados'),
        path('postulantes/clasedemo/', rectores.clasedemo, name='clasedemo'),
        path('postulantes/oferta/', rectores.oferta_view, name='oferta_view'),

        path('postulantes/entrevistas/', rectores.entrevista, name='entrevistas'),
        path('postulantes/<int:pk>/rubricas/', rectores.rubricas, name='rubricas'),
        path('postulantes/<int:pk>/rubrica/', rectores.rubrica, name='rubrica'),
        path('postulantes/<int:pk>/vista_rubrica/', rectores.vista_rubrica, name='vista_rubrica'),
        path('postulantes/<int:pk>/vista_rubrica_equipo/', rectores.vista_rubrica_equipo, name='vista_rubrica_equipo'),
        path('postulantes/<int:pk>/vista_rubrica_demo/', rectores.vista_rubrica_demo, name='vista_rubrica_demo'),
        path('postulantes/<int:pk>/vista_rubrica_psicologa/', rectores.vista_rubrica_psicologa, name='vista_rubrica_psicologa'),
        path('postulantes/<int:pk>/rubrica_equipo/', rectores.rubricaem, name='rubrica_em'),
        path('postulantes/<int:pk>/rubrica_demo/', rectores.rubricademo, name='rubrica_demo'),
        path('postulantes/<int:pk>/send/', rectores.send, name='send'),
        path('postulantes/<int:pk>/reportar/', rectores.reportar, name='reportar'),
        path('postulantes/<int:pk>/ficha/', rectores.subirficha, name='ficha'),
        path('postulantes/<int:pk>/oferta_laboral/', rectores.oferta, name='oferta'),

        path('finalizado', rectores.finalizados, name='fin'),






        path('postulantes/aprobados/',rectores.aprobados, name='aprobados'),
    ], 'CV_APP'), namespace='rectores')),

    path('psicologa/', include(([
        path('postulantes', psicologa.index, name='index'),
        path('postulantes/<int:pk>/vista_rubrica/', psicologa.vista_rubrica, name='vista_rubrica'),
        path('postulantes/<int:pk>/rubrica_coordinador/',psicologa.vista_rubricaC, name='vista_rubrica_coordinador'),
        path('postulantes/<int:pk>/rubrica_psicologica/', psicologa.rubrica, name='rubrica'),
        path('postulantes/entrevistados/',psicologa.entrevistados, name='entrevistados')
    ], 'CV_APP'), namespace='psicologa')),
    

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CV_APP/views/coordinacion.py
import json
import traceback
from itertools import chain
from .__init__ import *
from django.contrib.admin.models import LogEntry, ADDITION, CHANGE
from django.contrib.contenttypes.models import ContentType
from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, PatternFill, Font, Side
from openpyxl.drawing.image import Image
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.template.loader import get_template,render_to_string
from django.utils.html import strip_tags
from django.template import Context
from django.contrib import messages
from django.contrib.auth import login
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Avg, Count, Sum, Min, Max, Func
from django.contrib.auth.models import User
from django.forms import inlineformset_factory, modelformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (TemplateView,CreateView, DeleteView, DetailView, ListView,
                                  UpdateView, TemplateView, View)
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from rest_framework.views import APIView
from rest_framework.response import Response
from ..decorators import coordinacion_required

from CV_APP.models import Rubrica_demo, Rubrica_equipomulti, Años, Cargo, Colegios, Disposicion, Postulacion ,User, Rubrica_coordinador, Rubrica, Rubrica_psicologa
from CV_APP.forms import PostulacionForm, Postulantes, CoordinadorSignUpForm, RubricaCForm,Entrevistado


class CoordinadorSignUpView(CreateView):
    model = User
    form_class = CoordinadorSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'Coordinador'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('coordinacion:index')

@login_required
@coordinacion_required
def index_c(request):
    postulante = Postulacion.objects.filter(valido=False,rechazar=False, cargo=6)
    return render(request, "coordinacion/coordinadores/coordinadores.html", {'postulante':postulante})


@login_required
@coordinacion_required
def entrevistar_c(request):
    postulante = Postulacion.objects.filter(valido=True,rechazar=False, cargo=6, entrevistado=False)
    return render(request, "coordinacion/coordinadores/entrevistar.html", {'postulante':postulante})

@login_required
@coordinacion_required
def rechazados(request):
    postulante = Postulacion.objects.all()
    return render(request, "coordinacion/rechazados/rechazados.html", {'postulante':postulante})

@login_required
@coordinacion_required
def index(request):
    postulante = Postulacion.objects.filter(valido=False,rechazar=False)
    return render(request, "coordinacion/index.html", {'postulante':postulante})

@login_required
@coordinacion_required
def activos(request):
    postulante = Postulacion.objects.filter(valido=True, Siguiente=False)
    return render(request, "coordinacion/activos.html", {'postulante':postulante})

@login_required
@coordinacion_required
def proceso(request):
    postulante = Postulacion.objects.filter(valido=True,psicologa=True, rechazar=False, rechazar_rector=False,aprobar_demos=True, aceptada=False)
    return render(request, "coordinacion/proceso.html", {'postulante':postulante})

@login_required
@coordinacion_required
def psicolaboral(request):
    postulante = Postulacion.objects.filter(valido=True, entrevistado=True, rechazar=False, aprobar_demos=True, aceptada=False)
    return render(request, "coordinacion/psicolaboral.html", {'postulante':postulante})

@login_required
@coordinacion_required
def psicolaboral_c(request):
    postulante = Rubrica_coordinador.objects.filter(entrevistado=True,postulacion__psicologa=False, postulacion__aceptada=False)
    return render(request, "coordinacion/coordinadores/psicolaboral_c.html", {'postulante':postulante})

@login_required
@coordinacion_required
def finalizados(request):
    postulante = Postulacion.objects.filter(valido=True, entrevistado=True, rechazar=False, send=True, aceptada = True)

    return render(request, "coordinacion/finalizado.html",{'postulante':postulante})

@login_required
@coordinacion_required
def finalizados_c(request):
    postulante = Postulacion.objects.filter(valido=True, entrevistado=True, rechazar=False, send=True)

    return render(request, "coordinacion/coordinadores/finalizados.html",{'postulante':postulante})

@login_required
@coordinacion_required
def info(request, pk):
    postulante = get_object_or_404(Postulacion, pk=pk)
    if request.method == 'POST':
        form = Postulantes(request.POST, request.FILES, instance=postulante)
        if form.is_valid():
            with transaction.atomic():
                form.save()
            messages.success(request, 'Postulacion Aceptada')
            if postulante.cargo.id == 6:
                return redirect('coordinacion:entrevistar')
            else:
                return redirect('coordinacion:proceso')
    else:
        form = Postulantes(instance=postulante)
    return render(request, "coordinacion/info.html",{'postulante':postulante,'form':form})

@method_decorator([login_required, coordinacion_required] , name='dispatch')
class PostulanteDeleteView(DeleteView):
    model = Postulacion
    template_name = 'coordinacion/eliminar.html'
    success_url = reverse_lazy('coordinacion:index')

    def delete(self, request, *args, **kwargs):
        postulante = self.get_object()
        messages.success(request, 'La postulación fue borrada')
        return super().delete(request, *args, **kwargs)

@login_required
@coordinacion_required
def rubrica(request, pk):
    postulantes = get_object_or_404(Postulacion, pk=pk)
    rubrica = Rubrica_coordinador.objects.filter(postulacion=postulantes)
    if request.method == 'POST':
        form = Entrevistado(request.POST, request.FILES, instance=postulantes)
        formset = RubricaCForm(request.POST, request.FILES)
        if form.is_valid() and formset.is_valid():
            with transaction.atomic():
                postulante = form.save(commit=False)
                postulante.entrevistado = True
                rubrica = formset.save(commit=False)
                rubrica.owner = request.user

                rubrica.postulacion = postulantes 
                if rubrica.puntos == 1:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')
                if rubrica.puntos2 == 1:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')
                if rubrica.puntos3 == 1:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')
                if rubrica.puntos4 == 1:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')
                if rubrica.puntos5 == 1:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')
                if rubrica.puntos6 == 1:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')
                if rubrica.puntos7 == 1:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')
                
                if rubrica.puntos == 0:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')
                if rubrica.puntos2 == 0:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')
                if rubrica.puntos3 == 0:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')
                if rubrica.puntos4 == 0:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')
                if rubrica.puntos5 == 0:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')
                if rubrica.puntos6 == 0:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')
                if rubrica.puntos7 == 0:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')


CV_APP/views/cv.py
import json
import traceback
from itertools import chain
from .__init__ import *
from django.contrib.admin.models import LogEntry, ADDITION, CHANGE
from django.contrib.contenttypes.models import ContentType
from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, PatternFill, Font, Side
from openpyxl.drawing.image import Image
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.template.loader import get_template,render_to_string
from django.utils.html import strip_tags
from django.template import Context
from django.contrib import messages
from django.contrib.auth import login
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Avg, Count, Sum, Min, Max, Func
from django.contrib.auth.models import User
from django.forms import inlineformset_factory, modelformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (TemplateView,CreateView, DeleteView, DetailView, ListView,
                                  UpdateView, TemplateView, View)
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from rest_framework.views import APIView
from rest_framework.response import Response
from CV_APP.models import Años, Cargo, Colegios, Disposicion, Postulacion, User
from CV_APP.forms import PostulacionForm

def home(request):
    if request.user.is_authenticated:
        if request.user.is_coordinacion:
            return redirect('coordinacion:index')
        if request.user.is_rector:
            return redirect('rectores:index')
        if request.user.is_psicologa:
            return redirect('psicologa:index')
    return render(request, 'index.html')


def index(request):

    if request.method == 'POST':
        form = PostulacionForm(request.POST, request.FILES)
        if form.is_valid():
            postulacion = form.save(commit=False)
            postulacion.save()
            form.save_m2m()
            
            return redirect('index')
    else:
        form = PostulacionForm()
    
    return render(request, "home.html",{
        'form':form, 
        'successful_submit': True,
    })


def user_profile(request):
    
    return render(request, "user_profile.html")

CV_APP/templates/rector/clase_demostrativa.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'rector/header.html' with active='new5' %}
<br>
<div class="table-responsive">
    <table id="example" class=" table table-striped table-bordered display table-sm" >
        <thead>
            <tr>
                <th class="text-center" scope="col">Postulante</th>
                <th class="text-center" scope="col">Cargo</th>
                <th class="text-center" scope="col">Título</th>
                <th class="text-center" scope="col">Colegio</th>
                <th class="text-center">Fecha de postulación</th>
                <th>Rúbricas aplicadas</th>
                <th>Clase demostrativa</th>

            </tr>
        </thead>
        
        <tbody>
            {% for postulante in postulantes %}
            <tr>
                <td class="text-center"><a onclick="return abrir_modal('{% url 'rectores:info' postulante.postulacion.pk %}','Postulante')" data-toggle="tooltip"  title="Ver Información">{{postulante.postulacion.nombre}} {{postulante.postulacion.apellido_p}} {{postulante.postulacion.apellido_m}}</a></td>
                
                <td class="text-center">{{postulante.postulacion.cargo}}</td>
                <td class="text-center">{{postulante.postulacion.titulo}}</td>
                <td class="text-center"> {{postulante.postulacion.colegio1}} </td>
                <td class="text-center">{{postulante.postulacion.enviada|date:"d/m/Y"}}</td>
                <td class="text-center"> 
                    <a href="{% url 'rectores:vista_rubrica' postulante.pk %}" class="btn btn-primary btn-sm"> Ver entrevista</a>
                </td>   
                <td class="text-center">
                    <a href="{% url 'rectores:rubrica_demo' postulante.postulacion.pk %}" class="btn btn-primary btn-sm pulse">Clase Demostrativa</a>
                </td>            
                </tr> 
                       
            </tr>

        {% endfor %}

        {% for  postulantes in postulante %}
        <tr>
            <td class="text-center"><a onclick="return abrir_modal('{% url 'rectores:info' postulantes.postulacion.pk %}','Postulante')" data-toggle="tooltip"  title="Ver Información">{{postulantes.postulacion.nombre}} {{postulantes.postulacion.apellido_p}} {{postulantes.postulacion.apellido_m}}</a></td>
            
            <td class="text-center">{{postulantes.postulacion.cargo}}</td>
            <td class="text-center">{{postulantes.postulacion.titulo}}</td>
            <td class="text-center"> {{postulantes.postulacion.colegio1}} </td>
            <td class="text-center">{{postulantes.postulacion.enviada|date:"d/m/Y"}}</td>

            <td class="text-center"> 
                <a href="{% url 'rectores:vista_rubrica_equipo' postulantes.pk %}" class="btn btn-primary btn-sm"> Ver entrevista</a>
            </td>   
            <td class="text-center">
                <a href="{% url 'rectores:rubrica_demo' postulantes.postulacion.pk %}" class="btn btn-primary btn-sm pulse">Clase Demostrativa</a>
            </td>            
            </tr> 
                   
        </tr>
        {% endfor %}


        </tbody>
    </table>
    

</div>
{% endblock %}

CV_APP/templates/rector/entrevistas.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


{% include 'rector/header.html' with active='new2' %}

<br>

<div class="table-responsive">
    <table id="example" class=" table table-striped table-bordered display table-sm" >
        <thead>
            <tr>
                <th class="text-center">#</th>
                <th class="text-center" scope="col">Postulante</th>
                <th class="text-center" scope="col">Cargo</th>
                <th class="text-center" scope="col">Título</th>
                <th class="text-center" scope="col">Colegio</th>
                <th class="text-center" scope="col">CV</th>
                <th class="text-center" scope="col">Fecha</th>

                <th></th>

            </tr>
        </thead>
        
        <tbody>
        {% for postulante in postulantes %}
            <tr>
                <td class="text-center">{{forloop.counter}}</td>
                <td class="text-center"><a onclick="return abrir_modal('{% url 'rectores:info' postulante.pk %}','Postulante')" data-toggle="tooltip"  title="Ver Información">{{postulante.nombre}} {{postulante.apellido_p}} {{postulante.apellido_m}}</a></td>
                <td class="text-center">{{postulante.cargo}}</td>
                <td class="text-center">{{postulante.titulo}}</td>
                <td class="text-center"> {{postulante.colegio1}}</td>
                
                <td class="text-center"><a href="{{postulante.cv.url}}" target="_blank"><i class="fas fa-file-download"></i></a></td>
                <td class="text-center">{{postulante.enviada|date:"d/m/Y"}}</td>

                {% if postulante.cargo.id == 7 %}
                <td class="text-center">                   
                    <a href="{% url 'rectores:rubrica_em' postulante.pk %}" class="btn btn-primary btn-sm"> Entrevistar</a>

                </td>    
                {% else %}
                <td class="text-center">                   
                    <a href="{% url 'rectores:rubrica' postulante.pk %}" class="btn btn-primary btn-sm"> Entrevistar</a>

                </td>     
 
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>



</div>

<div id="popup"></div>



<script>
    var modal;
    function abrir_modal(url, titulo)
    {
        modal = $('#popup').dialog(
        {
            title: titulo,
            modal: true,
            width: 900,
            resizable: false
        }).dialog('open').load(url)
    }
    
    function cerrar_modal()
    {
        modal.dialog("close");
    }
</script>

{% endblock %}

CV_APP/templates/rector/header.html
{% if user.is_authenticated and user.is_rector %}
{% load static %}
<!--<link rel="stylesheet" href="{% static "css/menu.css" %}">--> 
{% for colegio in user.rector.colegio.all %}
<img src=" {{ colegio.imagen.url }} " class="img-fluid" style="width: 18%;"/>
{% endfor %}

<div class="text-right">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user"></i>  {{ user.first_name }}  {{user.last_name}}<span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><a href="{% url 'user' %}" target="_blank"> <i class="fas fa-user-cog"></i> Información de Usuario</a></li>
    <li><a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> Salir</a></li>
  </ul>
</div>



<br>

{% endif %}





<ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link {% if active == 'new' %} active{% endif %}"  href="{% url 'rectores:index' %}"  >Postulantes</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if active == 'new2' %} active{% endif %} "  href="{% url 'rectores:entrevistas' %}" >Entrevistas</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if active == 'new5' %} active{% endif %}" href="{% url 'rectores:clasedemo' %}">Clase Demostrativa</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if active == 'new4' %} active{% endif %}" href="{% url 'rectores:aprobados' %}">Aprobados Psicolaboral</a>
    </li>
    <li>
      <a class="nav-link {% if active == 'new8' %} active{% endif %}"  href="{% url 'rectores:oferta_view' %}">Oferta laboral</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if active == 'new6' %} active{% endif %}" href="{% url 'rectores:rechazados' %}">No sigue proceso</a>
    </li>

  <li class="nav-item">
      <a class="nav-link {% if active == 'new7' %} active{% endif %}" href="{% url 'rectores:fin' %}">Finalizados</a>
  </li>
  
</ul>

CV_APP/templates/rector/info2.html
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<p class="text-right text-muted">Fecha de postulación: {{postulante.enviada|date:"d/m/Y"}}</p>
<br>
<strong><p>Rut: {{postulante.rut}}</p></strong>

<p><strong>Cargo al que postula:</strong> {{postulante.cargo}} </p>
<p><strong>Colegio de preferencia:</strong> {{postulante.colegio1}}</p>
<p><strong>Colegio de preferencia 2:</strong> {{postulante.colegio2}}</p>
<p><strong>Colegio de preferencia 3:</strong> {{postulante.colegio3}}</p>
<p><strong>Años de experiencia:</strong> {{postulante.años}}</p>
<p ><strong>Telefóno:</strong> {{postulante.telefono}}</p>
<p><strong>Correo:</strong> {{postulante.email}}</p>


<form action="{% url 'rectores:info' postulante.pk %}" method="post" novalidate>
<br>
<div class="panel panel-default">
    <div class="panel-body">

    {% csrf_token %}



</div>
</div>
<div class="row" >
  <div class="col-lg-12 text-right" >
    <button type="button" class="btn btn-default" onclick="return cerrar_modal()">Cerrar</button>
  </div>
</div>


{% endblock %}

CV_APP/templates/rector/oferta_laboral.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}



<br>
<h1 class="text-center">Oferta Laboral</h1>
<p>Postulante: {{postulantes.nombre}} {{postulantes.apellido_p}} {{postulantes.apellido_m}} </p>
<p>Colegio: {{postulantes.colegio1}}</p>

<br>
<div class="text-center">

</div>

<div id="popup"></div>

<form method="post" enctype="multipart/form-data">

   
        
    {% csrf_token %}
    {{ form.aceptada|as_crispy_field }}
    {{form.rechazada|as_crispy_field}}


        <button type="submit" class="btn btn-success btn-md">Guardar</button> 

</form>
<script>
    var modal;
    function abrir_modal(url, titulo)
    {
        modal = $('#popup').dialog(
        {
            title: titulo,
            modal: true,
            width: 900,
            resizable: false
        }).dialog('open').load(url)
    }
    
    function cerrar_modal()
    {
        modal.dialog("close");
    }
</script>

{% endblock %}

CV_APP/templates/rector/rubricas.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

{% include 'rector/header.html'  %}


<br>
<h1 class="text-center">Rubricas</h1>
<p>Postulante: {{postulacion.nombre}} {{postulacion.apellido_p}} {{postulacion.apellido_m}} </p>
<p>Colegio: {{postulacion.colegio1}}</p>
<p>Correo: {{postulacion.email}} </p>

<br>
<div class="text-center">
{% for postulante in postulantes %}
<a href="{% url 'rectores:vista_rubrica' postulante.pk %}" class="btn btn-primary btn-sm"> Rúbrica entrevista rector</a>

{% endfor %}

{% for postulante_em in postulante_em %}
<a href="{% url 'rectores:vista_rubrica_equipo' postulante_em.pk %}" class="btn btn-primary btn-sm"> Rubrica Equipo Multidiciplinario</a>

{% endfor %}

{% for postulante_demo in postulante_demo %}
<a href="{% url 'rectores:vista_rubrica_demo' postulante_demo.pk %}" class="btn btn-primary btn-sm"> Rúbrica Clase Demostrativa</a>

{% endfor %}

{% for postulante_psicologa in postulante_psicologa %}
<a href="{% url 'rectores:vista_rubrica_psicologa' postulante_psicologa.pk %}" class="btn btn-primary btn-sm"> Rubrica psicologa</a>

{% endfor %}
</div>

<div id="popup"></div>


<script>
    var modal;
    function abrir_modal(url, titulo)
    {
        modal = $('#popup').dialog(
        {
            title: titulo,
            modal: true,
            width: 900,
            resizable: false
        }).dialog('open').load(url)
    }
    
    function cerrar_modal()
    {
        modal.dialog("close");
    }
</script>

{% endblock %}