CV/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from CV_APP.views import cv, coordinacion, rectores


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CV_APP.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/coordinador/', coordinacion.CoordinadorSignUpView.as_view(), name='coordinador_signup'),
    path('accounts/rector/', rectores.RectorSignUpView.as_view(), name='rector_signup'),



]

CV_APP/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from .views import cv, coordinacion, rectores, psicologa
urlpatterns = [
    path('postulacion', cv.index, name='index'),
    path('', cv.home, name='home'),
    path('user_profile', cv.user_profile, name='user'),
    path('coordinacion/', include(([
        path('postulantes', coordinacion.index, name='index'),
        path('rechazados', coordinacion.rechazados, name='rechazados'),
        path('finalizado', coordinacion.finalizados, name='fin'),
        path('finalizados', coordinacion.finalizados_c, name='fin_c'),

        path('coordinadores', coordinacion.index_c, name='coordinadores'),
        path('coordinadores/entrevistar', coordinacion.entrevistar_c, name='entrevistar'),
        path('coordinadores/<int:pk>/rubrica/', coordinacion.rubrica, name='rubrica'),
        path('postulantes/<int:pk>/rubricas/', coordinacion.rubricas, name='rubricas'),

        path('postulantes/<int:pk>/rubrica_rector/', coordinacion.vista_rubrica, name='vista_rubrica'),
        path('coordinadores/<int:pk>/rubrica_coordinador/', coordinacion.vista_rubricaC, name='vista_rubrica_coordinador'),
        path('postulantes/<int:pk>/vista_rubrica_equipo/', coordinacion.vista_rubrica_equipo, name='vista_rubrica_equipo'),
        path('postulantes/<int:pk>/vista_rubrica_equipo/', coordinacion.vista_rubrica_equipo, name='vista_rubrica_equipo'),
        path('postulantes/<int:pk>/vista_rubrica_demo/', coordinacion.vista_rubrica_demo, name='vista_rubrica_demo'),
        path('activos', coordinacion.activos, name='activos'),
        path('proceso', coordinacion.proceso, name='proceso'),
        path('psicolaboral', coordinacion.psicolaboral, name='psicolaboral'),
        path('psicolaboral_coordinador', coordinacion.psicolaboral_c, name='psicolaboral_c'),

        path('postulantes/<int:pk>/', coordinacion.info, name='info'),
        path('postulantes/<int:pk>/delete', coordinacion.PostulanteDeleteView.as_view(), name='borrar'),
    ], 'CV_APP'), namespace='coordinacion')),

    path('rectores/', include(([
        path('postulantes', rectores.index, name='index'),
        path('postulantes/<int:pk>/', rectores.info, name='info'),
        path('postulantes/<int:pk>/', rectores.info2, name='informacion2'),
        path('postulantes/rechazados/', rectores.cargo, name='rechazados'),
        path('postulantes/clasedemo/', rectores.clasedemo, name='clasedemo'),
        path('postulantes/oferta/', rectores.oferta_view, name='oferta_view'),

        path('postulantes/entrevistas/', rectores.entrevista, name='entrevistas'),
        path('postulantes/<int:pk>/rubricas/', rectores.rubricas, name='rubricas'),
        path('postulantes/<int:pk>/rubrica/', rectores.rubrica, name='rubrica'),
        path('postulantes/<int:pk>/vista_rubrica/', rectores.vista_rubrica, name='vista_rubrica'),
        path('postulantes/<int:pk>/vista_rubrica_equipo/', rectores.vista_rubrica_equipo, name='vista_rubrica_equipo'),
        path('postulantes/<int:pk>/vista_rubrica_demo/', rectores.vista_rubrica_demo, name='vista_rubrica_demo'),
        path('postulantes/<int:pk>/vista_rubrica_psicologa/', rectores.vista_rubrica_psicologa, name='vista_rubrica_psicologa'),
        path('postulantes/<int:pk>/rubrica_equipo/', rectores.rubricaem, name='rubrica_em'),
        path('postulantes/<int:pk>/rubrica_demo/', rectores.rubricademo, name='rubrica_demo'),
        path('postulantes/<int:pk>/send/', rectores.send, name='send'),
        path('postulantes/<int:pk>/reportar/', rectores.reportar, name='reportar'),
        path('postulantes/<int:pk>/ficha/', rectores.subirficha, name='ficha'),
        path('postulantes/<int:pk>/oferta_laboral/', rectores.oferta, name='oferta'),

        path('finalizado', rectores.finalizados, name='fin'),






        path('postulantes/aprobados/',rectores.aprobados, name='aprobados'),
    ], 'CV_APP'), namespace='rectores')),

    path('psicologa/', include(([
        path('postulantes', psicologa.index, name='index'),
        path('postulantes/<int:pk>/vista_rubrica/', psicologa.vista_rubrica, name='vista_rubrica'),
        path('postulantes/<int:pk>/rubrica_coordinador/',psicologa.vista_rubricaC, name='vista_rubrica_coordinador'),
        path('postulantes/<int:pk>/rubrica_psicologica/', psicologa.rubrica, name='rubrica'),
        path('postulantes/entrevistados/',psicologa.entrevistados, name='entrevistados')
    ], 'CV_APP'), namespace='psicologa')),
    

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CV_APP/views/coordinacion.py
import json
import traceback
from itertools import chain
from .__init__ import *
from django.contrib.admin.models import LogEntry, ADDITION, CHANGE
from django.contrib.contenttypes.models import ContentType
from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, PatternFill, Font, Side
from openpyxl.drawing.image import Image
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.template.loader import get_template,render_to_string
from django.utils.html import strip_tags
from django.template import Context
from django.contrib import messages
from django.contrib.auth import login
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Avg, Count, Sum, Min, Max, Func
from django.contrib.auth.models import User
from django.forms import inlineformset_factory, modelformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (TemplateView,CreateView, DeleteView, DetailView, ListView,
                                  UpdateView, TemplateView, View)
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from rest_framework.views import APIView
from rest_framework.response import Response
from ..decorators import coordinacion_required

from CV_APP.models import Rubrica_demo, Rubrica_equipomulti, Años, Cargo, Colegios, Disposicion, Postulacion ,User, Rubrica_coordinador, Rubrica, Rubrica_psicologa
from CV_APP.forms import PostulacionForm, Postulantes, CoordinadorSignUpForm, RubricaCForm,Entrevistado


class CoordinadorSignUpView(CreateView):
    model = User
    form_class = CoordinadorSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'Coordinador'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('coordinacion:index')

@login_required
@coordinacion_required
def index_c(request):
    postulante = Postulacion.objects.filter(valido=False,rechazar=False, cargo=6)
    return render(request, "coordinacion/coordinadores/coordinadores.html", {'postulante':postulante})


@login_required
@coordinacion_required
def entrevistar_c(request):
    postulante = Postulacion.objects.filter(valido=True,rechazar=False, cargo=6, entrevistado=False)
    return render(request, "coordinacion/coordinadores/entrevistar.html", {'postulante':postulante})

@login_required
@coordinacion_required
def rechazados(request):
    postulante = Postulacion.objects.all()
    return render(request, "coordinacion/rechazados/rechazados.html", {'postulante':postulante})

@login_required
@coordinacion_required
def index(request):
    postulante = Postulacion.objects.filter(valido=False,rechazar=False)
    return render(request, "coordinacion/index.html", {'postulante':postulante})

@login_required
@coordinacion_required
def activos(request):
    postulante = Postulacion.objects.filter(valido=True, Siguiente=False)
    return render(request, "coordinacion/activos.html", {'postulante':postulante})

@login_required
@coordinacion_required
def proceso(request):
    postulante = Postulacion.objects.filter(valido=True,psicologa=True, rechazar=False, rechazar_rector=False,aprobar_demos=True, aceptada=False)
    return render(request, "coordinacion/proceso.html", {'postulante':postulante})

@login_required
@coordinacion_required
def psicolaboral(request):
    postulante = Postulacion.objects.filter(valido=True, entrevistado=True, rechazar=False, aprobar_demos=True, aceptada=False)
    return render(request, "coordinacion/psicolaboral.html", {'postulante':postulante})

@login_required
@coordinacion_required
def psicolaboral_c(request):
    postulante = Rubrica_coordinador.objects.filter(entrevistado=True,postulacion__psicologa=False, postulacion__aceptada=False)
    return render(request, "coordinacion/coordinadores/psicolaboral_c.html", {'postulante':postulante})

@login_required
@coordinacion_required
def finalizados(request):
    postulante = Postulacion.objects.filter(valido=True, entrevistado=True, rechazar=False, send=True, aceptada = True)

    return render(request, "coordinacion/finalizado.html",{'postulante':postulante})

@login_required
@coordinacion_required
def finalizados_c(request):
    postulante = Postulacion.objects.filter(valido=True, entrevistado=True, rechazar=False, send=True)

    return render(request, "coordinacion/coordinadores/finalizados.html",{'postulante':postulante})

@login_required
@coordinacion_required
def info(request, pk):
    postulante = get_object_or_404(Postulacion, pk=pk)
    if request.method == 'POST':
        form = Postulantes(request.POST, request.FILES, instance=postulante)
        if form.is_valid():
            with transaction.atomic():
                form.save()
            messages.success(request, 'Postulacion Aceptada')
            if postulante.cargo.id == 6:
                return redirect('coordinacion:entrevistar')
            else:
                return redirect('coordinacion:proceso')
    else:
        form = Postulantes(instance=postulante)
    return render(request, "coordinacion/info.html",{'postulante':postulante,'form':form})

@method_decorator([login_required, coordinacion_required] , name='dispatch')
class PostulanteDeleteView(DeleteView):
    model = Postulacion
    template_name = 'coordinacion/eliminar.html'
    success_url = reverse_lazy('coordinacion:index')

    def delete(self, request, *args, **kwargs):
        postulante = self.get_object()
        messages.success(request, 'La postulación fue borrada')
        return super().delete(request, *args, **kwargs)

@login_required
@coordinacion_required
def rubrica(request, pk):
    postulantes = get_object_or_404(Postulacion, pk=pk)
    rubrica = Rubrica_coordinador.objects.filter(postulacion=postulantes)
    if request.method == 'POST':
        form = Entrevistado(request.POST, request.FILES, instance=postulantes)
        formset = RubricaCForm(request.POST, request.FILES)
        if form.is_valid() and formset.is_valid():
            with transaction.atomic():
                postulante = form.save(commit=False)
                postulante.entrevistado = True
                rubrica = formset.save(commit=False)
                rubrica.owner = request.user

                rubrica.postulacion = postulantes 
                if rubrica.puntos == 1:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')
                if rubrica.puntos2 == 1:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')
                if rubrica.puntos3 == 1:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')
                if rubrica.puntos4 == 1:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')
                if rubrica.puntos5 == 1:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')
                if rubrica.puntos6 == 1:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')
                if rubrica.puntos7 == 1:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')
                
                if rubrica.puntos == 0:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')
                if rubrica.puntos2 == 0:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')
                if rubrica.puntos3 == 0:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')
                if rubrica.puntos4 == 0:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')
                if rubrica.puntos5 == 0:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')
                if rubrica.puntos6 == 0:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')
                if rubrica.puntos7 == 0:
                    postulante.rechazar_rector = True
                    messages.success(request, 'Rubrica rechazada puesto que ah evaluado con 0 o 1 en algún segmento.')


CV_APP/views/cv.py
import json
import traceback
from itertools import chain
from .__init__ import *
from django.contrib.admin.models import LogEntry, ADDITION, CHANGE
from django.contrib.contenttypes.models import ContentType
from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, PatternFill, Font, Side
from openpyxl.drawing.image import Image
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.template.loader import get_template,render_to_string
from django.utils.html import strip_tags
from django.template import Context
from django.contrib import messages
from django.contrib.auth import login
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Avg, Count, Sum, Min, Max, Func
from django.contrib.auth.models import User
from django.forms import inlineformset_factory, modelformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (TemplateView,CreateView, DeleteView, DetailView, ListView,
                                  UpdateView, TemplateView, View)
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from rest_framework.views import APIView
from rest_framework.response import Response
from CV_APP.models import Años, Cargo, Colegios, Disposicion, Postulacion, User
from CV_APP.forms import PostulacionForm

def home(request):
    if request.user.is_authenticated:
        if request.user.is_coordinacion:
            return redirect('coordinacion:index')
        if request.user.is_rector:
            return redirect('rectores:index')
        if request.user.is_psicologa:
            return redirect('psicologa:index')
    return render(request, 'index.html')


def index(request):

    if request.method == 'POST':
        form = PostulacionForm(request.POST, request.FILES)
        if form.is_valid():
            postulacion = form.save(commit=False)
            postulacion.save()
            form.save_m2m()
            
            return redirect('index')
    else:
        form = PostulacionForm()
    
    return render(request, "home.html",{
        'form':form, 
        'successful_submit': True,
    })


def user_profile(request):
    
    return render(request, "user_profile.html")

CV_APP/templates/psicologa/entrevistados.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


{% include 'psicologa/header.html' with active='new2' %}

<br>

<div class="table-responsive">
    <table id="example" class=" table table-striped table-bordered display table-sm" >
        <thead>
            <tr>
                <th scope="col">Postulante</th>
                <th scope="col">Cargo</th>
                <th scope="col">Colegio</th>
                <th scope="col">Disponibilidad</th>
                <th scope="col">Años Experiencia</th>
                <th scope="col">CV</th>
                <th></th>
                <th></th>

            </tr>
        </thead>
        
        <tbody>
        {% for postulante in postulantes %}
            <tr>
                <td>{{postulante.postulacion.nombre}} {{postulante.postulacion.apellido_p}} {{postulante.postulacion.apellido_m}}</td>
                <td>{{postulante.postulacion.cargo}}</td>
                <td> {{postulante.postulacion.colegio1}}</td>
                <td>{% for disponibilidad in postulante.postulacion.disponibilidad.all %} |{{disponibilidad.name}}|  {% endfor %}</td>
                
                <td>{{postulante.postulacion.años}}</td >
                <td><a href="{{postulante.postulacion.cv.url}}" target="_blank">Descargar</a></td>

                <td>                   
                    <a href="{% url 'psicologa:vista_rubrica' postulante.pk %}" class="btn btn-primary btn-sm"> Rúbrica</a>
                </td>     
                <td>                   
                    <a href="" class="btn btn-primary btn-sm"> Psicologica</a>
                </td>                            
            </tr>
        {% endfor %}
            {% for rubrica in rubrica %}
            {% if rubrica.opcion_1_1.value == 1 %}
                <p>bajo lo esperado</p>
            {% endif %}
            {{rubrica.opcion_1_2}}
            
            {{rubrica.opcion_1_3}}
            {% endfor %}
        </tbody>
    </table>



</div>

<div id="popup"></div>



<script>
    var modal;
    function abrir_modal(url, titulo)
    {
        modal = $('#popup').dialog(
        {
            title: titulo,
            modal: true,
            width: 500,
            resizable: false
        }).dialog('open').load(url)
    }
    
    function cerrar_modal()
    {
        modal.dialog("close");
    }
</script>

{% endblock %}

CV_APP/templates/psicologa/header.html
{% load static %}
<!--<link rel="stylesheet" href="{% static "css/menu.css" %}">--> 

<img class="img-thumbnail" src="{% static "img/logo.jpg" %}" alt="" width="200" height="100">


<div class="text-right">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user"></i> <!-- {{ user.first_name }}  {{user.last_name}}-->Psicologa<span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><a href="{% url 'user' %}" target="_blank"> <i class="fas fa-user-cog"></i> Información de Usuario</a></li>
    <li><a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> Salir</a></li>
  </ul>
</div>


<ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link {% if active == 'new' %} active{% endif %}"  href="{% url 'psicologa:index' %}"  >Postulantes</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if active == 'new2' %} active{% endif %} " href="{% url 'psicologa:entrevistados' %}">Entrevistados</a>
    </li>
</ul>

CV_APP/templates/psicologa/index.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


{% include 'psicologa/header.html' with active='new' %}

<br>

<div class="table-responsive">
    <table id="example" class=" table table-striped table-bordered display table-sm" >
        <thead>
            <tr>
                <th style="text-align: center;" scope="col">Postulante</th>
                <th style="text-align: center;" scope="col">Cargo</th>
                <th scope="col">Colegio</th>
                <th style="text-align: center;" scope="col">Años Experiencia</th>
                <th style="text-align: center;" scope="col">CV</th>
                <th style="text-align: center;" scope="col">Fecha</th>

                <th></th>
                <th></th>

            </tr>
        </thead>
        
        <tbody>
        {% for postulante in postulantes %}
            <tr>
                <td class="text-center">{{postulante.postulacion.nombre}} {{postulante.postulacion.apellido_p}} {{postulante.postulacion.apellido_m}}</td>
                <td class="text-center">{{postulante.postulacion.cargo}}</td>
                <td class="text-center"> {{postulante.postulacion.colegio1}}</td>
                
                <td style="text-align: center;">{{postulante.postulacion.años}}</td >
                <td class="text-center"><a href="{{postulante.postulacion.cv.url}}" target="_blank"><i class="fas fa-file-download"></i></a></td>
                <td class="text-center">{{postulante.postulacion.enviada|date:"d/m/Y"}}</td>

                <td class="text-center">                   
                    <a href="{% url 'psicologa:vista_rubrica' postulante.pk %}" class="btn btn-primary btn-sm"> Rubrica</a>
                </td>     
                <td class="text-center">                   
                    <a href="{% url 'psicologa:rubrica' postulante.postulacion.pk %}" class="btn btn-primary btn-sm pulse"> Entrevistar</a>
                </td>                            
            </tr>
        {% endfor %}
        {% for postulantes_c in postulantes_c %}
        <tr>
            <td class="text-center">{{postulantes_c.postulacion.nombre}} {{postulantes_c.postulacion.apellido_p}} {{postulante_c.postulacion.apellido_m}}</td>
            <td class="text-center">{{postulantes_c.postulacion.cargo}}</td>
            <td  class="text-center" style="text-align: center;"> {{postulantes_c.postulacion.colegio1}}</td>
            
            <td class="text-center" style="text-align: center;">{{postulantes_c.postulacion.años}}</td >
            <td class="text-center"><a href="{{postulantes_c.postulacion.cv.url}}" target="_blank"><i class="fas fa-file-download"></i></a></td>
            <td class="text-center">{{postulantes_c.postulacion.enviada|date:"d/m/Y"}}</td>

            <td class="text-center">                   
                <a href="{% url 'psicologa:vista_rubrica_coordinador' postulantes_c.pk %}" class="btn btn-primary btn-sm"> Rubrica</a>
            </td> 
            <td class="text-center">                   
                <a href="{% url 'psicologa:rubrica' postulantes_c.postulacion.pk %}" class="btn btn-primary btn-sm pulse"> Entrevistar</a>
            </td>                            
        </tr>
        {% endfor %}

        {% for postulantes_c in postulante_em %}
        <tr>
            <td class="text-center">{{postulantes_c.postulacion.nombre}} {{postulantes_c.postulacion.apellido_p}} {{postulante_c.postulacion.apellido_m}}</td>
            <td class="text-center">{{postulantes_c.postulacion.cargo}}</td>
            <td  class="text-center" style="text-align: center;"> {{postulantes_c.postulacion.colegio1}}</td>            
            <td class="text-center" style="text-align: center;">{{postulantes_c.postulacion.años}}</td >
            <td class="text-center"><a href="{{postulantes_c.postulacion.cv.url}}" target="_blank"><i class="fas fa-file-download"></i></a></td>
            <td class="text-center">{{postulante.enviada|date:"d/m/Y"}}</td>

            <td class="text-center">                   
                <a href="" class="btn btn-primary btn-sm"> Rubrica</a>
            </td> 
            <td class="text-center">                   
                <a href="{% url 'psicologa:rubrica' postulantes_c.postulacion.pk %}" class="btn btn-primary btn-sm pulse"> Entrevistar</a>
            </td>                            
        </tr>
        {% endfor %}
        </tbody>
    </table>



</div>

<div id="popup"></div>



<script>
    var modal;
    function abrir_modal(url, titulo)
    {
        modal = $('#popup').dialog(
        {
            title: titulo,
            modal: true,
            width: 500,
            resizable: false
        }).dialog('open').load(url)
    }
    
    function cerrar_modal()
    {
        modal.dialog("close");
    }
</script>

{% endblock %}